# Generated by Django 5.0 on 2023-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-06-21'),
            preserve_default=False,
        ),
    ]
